project         = "kavi-prod-airflow-dags"
env             = "prod"
app             = "airflow-dag"
region          = "us-central1"
zone            = "us-central1-a"
db_machine_type = "db-custom-1-3840"